### ISSUE TITLE
Please add capability to allow hook to read from stdin instead of /dev/tty

### ISSUE THREAD

**Issue by nneul** [lukas2511/letsencrypt.sh#101]
Right now, the way it's written, hooks can't do normal IO then get immediate EOF.

While it's straightforward enough to run under expect/whatever, would be nice if a simple read/prompt would work.

**Comment by lukas2511** [comment]
I actually have no idea what you are asking for.

Hooks are just called as simple commands in the script with all data passed as arguments, there is no need to read from anywhere.

**Comment by nneul** [comment]
In my case when testing, I was an interactive prompt in the hook (wasn't fully automated). With the way it's currently implemented, you can't read from stdin in the hook - you can only read from /dev/tty. 

i.e. if you do "read x" in a hook shell script, it will immediately exit

**Comment by lukas2511** [comment]
I see what you mean, but I'm not entirely sure why this happens...

**Comment by nneul** [comment]
Found it. It's from this in command_sign_domains:
```
 <"${DOMAINS_TXT}" _sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*$//g' -e 's/[[:space:]]+/ /g' | (grep -vE '^(#|$)' || true) | while read -r line; do
```

During the entire loop, stdin is captured.  Have a pr coming.

**Comment by nneul** [comment]
What about this implementation #110
