### ISSUE TITLE
Fix storage directory

### ISSUE THREAD

**Issue by reetp** [lukas2511/letsencrypt.sh#104]
The certs get put in the following directory structure

/etc/letsencrypt.sh/certs/{some.domain}
/etc/letsencrypt.sh/certs/{other.domain}

I have a requirement to keep them in one directory which is not dictated by the domain names. This is handy in circumstances when the server with letsencrypt may not actually use the certificates itself.

The fix is quite easy - I can do a pull request but wanted you to check the following and see if it would be accepted:

in config.sh add variable if required:
LOCDIR="storage"

In letsencrypt.sh add the following line - defaults to domain name if LOCDIR not set:

Create certificate for domain(s)
sign_domain() {
  domain="${1}"
+  locdir="${LOCDIR:-$domain}"

Replace all instances of

/certs/${domain}

with 

/certs/${LOCDIR}

**Comment by lukas2511** [comment]
You can use hooks to move certificates to other directories or even upload them to other servers, whatever you need.

**Comment by the-solipsist** [comment]
Would it be possible to include an example in hook.sh.example of how to move these automatically to /etc/ssl/private?  It'd greatly help us noobs.  Thanks!

**Comment by lukas2511** [comment]
@the-solipsist there are some examples in the wiki, i may add more, but in the repository i want to keep the hook example as clean as possible
