### ISSUE TITLE
per-certificate config files

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/letsencrypt.sh#105]
It would be nice to have additional config files per-certificate to allow for certificate-specific options like RENEW_DAYS and PRIVATE_KEY_RENEW.

This replaces issue #34.

**Comment by srvrco** [comment]
Any specific location in mind ?    how about in the ${BASEDIR}/certs/${domain}/ folder  then each cert domain could overwrite the defaults set in the main config ( if it needed anything different ) and just use the defaults if not. 

have a quick look at https://github.com/srvrco/getssl  - I wrote it primarily because I wanted different defaults on different domains, and also wanted to be able to copy the challenges and final certs to remote servers ( ssh / scp) ..... If you are happy for that additional functionality  - I can look at adding multiple configs and effectively combining ( separate configs per domain / remote servers )  in to your script ?  (and effectively removing mine )

**Comment by lukas2511** [comment]
Yea, I was thinking to allow for `config.sh` next to the certificates in the target directory.

For implementation I guess the best thing would be to move certificate-specific code to a new function and use `local` variables, but this has to be implemented clean, variables should never be carried over to the next call of the function, because that would mess with other certificates.

**Comment by srvrco** [comment]
agreed.   I'm away this weekend - I'll take a closer look at your code early next week.

**Comment by iiidefix** [comment]
I would prefer to have a set of certificates with the same settings without creating a config for every certificate that is different from the main config but identical with at least some other configs.


Two ideas to make this possible:

1. make the `domains.txt` customisable via `config.sh`. This allows to run `letsencrypt.sh` first with default settings and `domains.txt`. And then run it with `-f config2.sh` which points to `domains2.txt`.
2. extent the syntax of `domains.txt`. Add a line starting with a colon `:` (a character not allowed in domains). And specify a custom `config.sh` there which merges with the current config and is valid for all following domains. 

In every scenario that uses multiple configuration files we should add a debug option which just outputs all configuration values per domain(set) and does nothing else.

**Comment by srvrco** [comment]
I was thinking more of a priority system, so in effect there are defaults within the code ( if no config files are specified ).   The main config file could then be used to modify this default.    Anything at the certificate level would use these unless there was a value in a certificate specific config file which would overwrite the earlier values.

**Comment by lukas2511** [comment]
Yes, idea was to have those specific configs as optional config files overriding some parameters for a single certificate, not having them as a requirement.

**Comment by iiidefix** [comment]
I like the idea to overwrite parameters for a single certificate. 
Additionally it would be great to have the possibility to overwrite specific parameters for a group of certificates at once. 
The reason for this are two domains registered by different resellers with different DNS-APIs.

- http-01 as default verification method for
  - example.com www.example.com
  - example.net www.example.net
  - webmail.example.com
- dns-01 with hook1.sh for DNS-API1:
  - smtp.example.com
  - imap.example.com
- dns-01 with hook2.sh for DNS-API2:
  - ipv6-only.example.net

With this setup it would be great to have two separate hooks. One for challenge handling and another one for certificate deployment and service restart.

**Comment by lukas2511** [comment]
Well, you could always use symlinks to have a shared config for multiple certs.

But maybe this could also be implemented with the help of a hook script so that people could script this...

**Comment by bax-** [comment]
+1
I would love to set different locations and hooks for certain domains

**Comment by bax-** [comment]
I like this idea a lot.
For certain domains it might even be good to have a RSA and an ECDSA key available:
http://www.postfix.org/TLS_README.html
Would be great to have this choice too.

**Comment by lukas2511** [comment]
This is now implemented in ec48906992ca9e1238dbcc9659e576cdd6bbeb07. See https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/per-certificate-config.md for more information
