### ISSUE TITLE
Add example for using DNS-01 challenge

### ISSUE THREAD

**Issue by jmreicha** [lukas2511/letsencrypt.sh#117]
I am new to LE in general and while the description for using the challenge type is nice, it would be helpful to someone new to have an example usage.

**Comment by germeier** [comment]
My example from my initial PR: https://github.com/germeier/letsencrypt.sh/blob/b6611a7d05c0171db01a5dd904fb0da052d753b8/hook-dns-01.sh.example

I still think an examples section in the wiki would come in handy.

**Comment by lukas2511** [comment]
@germeier the wiki is now writable (again), if you want you can add some examples

**Comment by germeier** [comment]
Added my example script to the wiki: https://github.com/lukas2511/letsencrypt.sh/wiki/Example-hook-script-using-dns-01-with-nsupdate

**Comment by jmreicha** [comment]
Nice, thanks.  Maybe this can get a link in the readme?

**Comment by asimihsan** [comment]
I've successfully used the following hook script to do the DNS challenge on Route53:

https://gist.github.com/asimihsan/d8d8f0f10bdc85fc6f8a

The idea is simple: you need to add the token as a TXT record to `_acme-challenge.#{domain}.`. However, a) this code isn't refactored very well, and b) on lines 19 and 45 you get the hosted zone with the name the same as the requested domain. Hence it won't work as-is if you request e.g `sub.domain.com`, since you need to search for `domain.com`.

If you think this script is useful I can refactor it and make it more resilient to work as-is for subdomains.

**Comment by lukas2511** [comment]
Added a wiki page with links to those examples: https://github.com/lukas2511/letsencrypt.sh/wiki/Examples-for-DNS-01-hooks

**Comment by AnalogJ** [comment]
Hey, 
I created a simple library called [lexicon](https://github.com/AnalogJ/lexicon) that lets you manipulate DNS records on various cloud DNS providers in a standardized way. It was built specifically for use with letsencrypt.sh and has [example cloudflare hook file](https://github.com/AnalogJ/lexicon/blob/master/examples/letsencrypt.cloudflare.sh) based off of @germeier's work. To use a different provider all you need to do is change 1 line in the example hook file. 

    python cli.py cloudflare create www.example.com TXT \
    --name "_acme-challenge.www.example.com." --content "challenge token"

Currently it only supports Cloudflare and PointHQ, but I'm happy to merge PR's for additional providers. 

Thanks for letsencrypt.sh btw, I'm a huge fan.

**Comment by YasharF** [comment]
Did lexicon or other integration for automating dns-01 challenge get added at some point?

**Comment by AnalogJ** [comment]
Hey @YasharF 
It doesn't require any changes to `dehydrated` to support automated dns-01 challenges, just a hook file that calls `lexicon`. 

I wrote a [blog post](http://blog.thesparktree.com/post/138999997429/generating-intranet-and-private-network-ssl) which fully explains how to get `lexicon` to work with `dehydrated` (though its a bit outdated now). The `lexicon` repo includes an up-to-date [Dockerfile](https://github.com/AnalogJ/lexicon/blob/master/Dockerfile) which installs `dehydrated`, and configures both correctly. If you still need help feel free to open an issue in the [lexicon repo](https://github.com/AnalogJ/lexicon)
