### ISSUE TITLE
LibreSSL support

### ISSUE THREAD

**Issue by maschs** [lukas2511/letsencrypt.sh#120]
Having libressl (`LibreSSL 2.3.2`) in your path breaks the script since libressl does not support `sha`. 

```
openssl:Error: 'sha' is an invalid command.
Message Digest commands (see the 'dgst' command for more details)
gost-mac          md4               md5               md_gost94
ripemd160         sha1              sha224            sha256
sha384            sha512            streebog256       streebog512
whirlpool
```

Maybe add the possibility to override the openssl binary path in the config file?

What I do right now is forcing the path manually:

```bash
sudo sh -c 'PATH="/usr/bin:$PATH";./letsencrypt.sh --cron --force -f config.sh'
```

**Comment by lukas2511** [comment]
I think the correct solution would be to use `openssl dgst -sha256` in the script. `openssl sha` seems to be a legacy command. This will be fixed soon.
