### ISSUE TITLE
add altname extension only when needed

### ISSUE THREAD

**Issue by bjacke** [lukas2511/letsencrypt.sh#121]
when there is just one domain name configured for a certificate, the CSR shoud be done without altname extension. Currelty requesting a cert for

foo.example.com

will result in
            X509v3 Subject Alternative Name: 
                DNS:foo.example.com

being added to the CSR and in the resulting certificate.

**Comment by lukas2511** [comment]
Is that bad in any way?

**Comment by bjacke** [comment]
On 05.02.2016 15:59, Lukas Schauer wrote:
> Is that bad in any way?

it's not exactly bad - it's just superfluous, makes the cert some bytes
larger for no reason. No big deal if you don't want to change this.
