### ISSUE TITLE
ECDSA error

### ISSUE THREAD

**Issue by rememberli** [lukas2511/letsencrypt.sh#123]
Hello, ECDSA is now supported , but I got error message as below,could you pls check where 
is problem ?
xxx@xxx[14:50:22]:~/ssl$./letsencrypt.sh -c -a secp384r1   
#
 WARNING !! No main config file found, using default config!
#
Processing sectun.com with alternative names: www.xxx.com
 + Signing domains...
 + Creating new directory /home/lisheng/ssl/certs/sectun.com ...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for xxx.com...
 + Requesting challenge for www.xxx.com...
 + Responding to challenge for xxx.com...
 + Challenge is valid!
 + Responding to challenge for xxx.sectun.com...
 + Challenge is valid!
 + Requesting certificate...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 400)

Details:           
{"type":"urn:acme:error:malformed","detail":"Invalid key in certificate request :: ECDSA curve P-384 not allowed","status":400}

**Comment by germeier** [comment]
I believe EC-384 is still not available on the production servers:

https://community.letsencrypt.org/t/problem-issuing-ec-384-certificate/9982

**Comment by rememberli** [comment]
It looks they are testing now,but I'm not sure if they are ready

https://community.letsencrypt.org/t/ecdsa-testing-on-staging/8809/54
