### ISSUE TITLE
Basic dns-01 hook script

### ISSUE THREAD

**Issue by NoodlesNZ** [lukas2511/letsencrypt.sh#125]
Can you please include an example of an extremely basic hook script for dns-01 like you explain in the README.md:

```
That could be done manually (as most providers don't have a DNS API), by having your hook script echo $1, $2 and $4 and then wait (read -s -r -e < /dev/tty) - give it a little time to get into their DNS system
```
I'm working on a script that will work with Akamai's DNS product, but for now I'd like to get a few domains working.
Thanks

**Comment by lukas2511** [comment]
Take a look at the wiki: https://github.com/lukas2511/letsencrypt.sh/wiki/Examples-for-DNS-01-hooks
