### ISSUE TITLE
keys: create per domain, create entropy

### ISSUE THREAD

**Issue by bax-** [lukas2511/letsencrypt.sh#128]
It would be great to have an option for creating a separate key for every domain in use.
It would also be nice if it would be possible to create some entropy before regenerating keys, just like calomel does:
https://calomel.org/lets_encrypt_client.html

**Comment by lukas2511** [comment]
Certificate keys are per certificate, the only shared part is the account key.

Generating entropy shouldn't be the job of this script, if you are running low on entropy you should run haveged or configure some other way of generating entropy.
