### ISSUE TITLE
clean up old certificates and keys

### ISSUE THREAD

**Issue by bax-** [lukas2511/letsencrypt.sh#130]
old keys and certificates are cumulating in the certs folders at the moment.
Is there a mechanism to delete old ones?

**Comment by lukas2511** [comment]
related to #80.
there will definitively be a feature for this in the future, but i kinda want to just move them to some kind of archive directory and not delete them directly.

**Comment by lukas2511** [comment]
I've implemented a solution in e60682c06c52cc52799f1eeecc178dbc3618ffdc.

**Comment by bax-** [comment]
great, thank you!
