### ISSUE TITLE
different exit value when a certificate is renewed

### ISSUE THREAD

**Issue by tobyblake** [lukas2511/letsencrypt.sh#132]
Hi there, firstly thanks for letsencrypt.sh - it looks to be really useful in my testing so far.  One thing that would be very nice would be if you could indicate when a certificate has been renewed with a different exit value - that would enable me to automate things like restarting of apache, etc. without having to grep through the output from letsencrypt.sh.

Cheers
Toby

**Comment by germeier** [comment]
My solution for this is to use a hook script. When the hook script is called with "deploy_cert" I know exactly which certificate is new and can do the correct stuff to activate the new cert.

**Comment by tobyblake** [comment]
Ah, that is nice - thanks for that.

**Comment by lukas2511** [comment]
I am against changing the return code as "0" is for success, and that is what should be used when the script ends successfully.

Some people wanted a feature that only checks if all certificates are still valid.  
I have an idea on how to implement this without duplicating a lot of code and will do that soon.
