### ISSUE TITLE
script for hooks can not be found

### ISSUE THREAD

**Issue by beelbrecht** [lukas2511/letsencrypt.sh#142]
Hi,

I'm using this config to specify the path of my hook.sh script:

`HOOK="${BASEDIR}/hook.sh"`

But my BASEDIR starts with `/Volumes/Macintosh HD/Users`
There is a space in the pathname. Why not adding double quotes to the hook variable ${HOOK} in letsencrypt.sh?
My shell script knowledge ist not very well, but this solution works for me...

Kind regards,
Benjamin

**Comment by lukas2511** [comment]
oh yea, spaces do exist, i always forget.

**Comment by K2rool** [comment]
Hi, this commit cusses hook script not to be loaded  ./letsencrypt.sh: line 410: python hooks/cloudflare/hook.py: No such file or directory, i manage to get it working by undoing all the change this commit dose by removed all the double quotes which was added.

**Comment by lukas2511** [comment]
@K2rool just use `hooks/cloudflare/hook.py`, add a shebang to the first line of your script `#!/usr/bin/env python` and make it executable (`chmod +x hooks/cloudflare/hook.py`).

**Comment by K2rool** [comment]
@lukas2511  Thanks that fixed it, i got letsencrypt.sh on a few server i coped the config file from one of my other server which must be running a letsencrypt.sh before this commit.

Thank for the quick reply and helping me fix my issue

**Comment by bviktor** [comment]
Unfortunately this does not work for Java where you don't have a shebang.

~~~
./letsencrypt.sh: line 616: java -jar /opt/certzure/certzure.jar: No such file or directory
~~~

Any ideas how to solve this, other than creating a passthrough shell script?

**Comment by bviktor** [comment]
The only other thing I can think of ATM is an additional, optional argument, "hook interpreter", that could contain "sh", "python2.7", "java -jar" or whatever. Opinions?

**Comment by lukas2511** [comment]
@bviktor I think a passthrough/wrapper script would be better than a new option. It's simple, it doesn't add much weight and it can handle all kind of edgecases.

**Comment by bviktor** [comment]
Alright.
