### ISSUE TITLE
convert to POSIX.sh / styleguide

### ISSUE THREAD

**Issue by bittorf** [lukas2511/letsencrypt.sh#145]
i want to send some PullRequests for converting the whole script to POSIX sh.
this issue is just for collecting some questions and answers on this regarding style.

**Comment by bittorf** [comment]
Q: is there a good reason why your are alway using [[ -switch ... ]] instead of just [ -switch ... ] ? e.g.
```
if [[ ! "${retcode}" = "0" ]] &&
```
can be converted to
```
[ $retcode -eq 0 ] || ...
```

**Comment by bittorf** [comment]
Q: why are we always enclosing var with "${var}" even when it is unneeded? every texteditor does already highlight the variables.

**Comment by lukas2511** [comment]
Using `[[` instead of `[` because `[[` is a shell built-in while `[` (in theory) is a command, making the script (in theory) a bit cleaner.

Using `${var}` instead of `$var` just as a habit and to never ever run into any problems. Also it feels good to have it consistent.

**Comment by bittorf** [comment]
@lukas2511 i'am OK with using ${var} - it's just a style issue.

**Comment by bittorf** [comment]
@lukas2511 i understand the reason for "[[" but i'am not happy. is it OK for you when i convert them to single ones, "[[" is not defined in POSIX.

**Comment by lukas2511** [comment]
@bittorf yes, i would be okay with that if you can work out the other stuff to make it posix compatible.

**Comment by bittorf** [comment]
ok, i will start to send small pullrequests...

**Comment by 166MMX** [comment]
I have been [playing around](https://travis-ci.org/166MMX/letsencrypt.sh) with Travis CI and [ShellCheck](https://github.com/koalaman/shellcheck). Maybe it is some sort of help for you guys.

I am new to Travis CI that's why I replaced the content of the yaml file. Not sure how to integrate that into your existing one though.

**Comment by lukas2511** [comment]
I'm closing this ticket now. Doesn't look like anybody is working on this and I don't really have a personal interest at doing this migration. If somebody still wants letsencrypt.sh to be POSIX sh compatible please feel free to open pull-requests.
