### ISSUE TITLE
Add an option to automatically print the certificate plus the intermediate one

### ISSUE THREAD

**Issue by ThiefMaster** [lukas2511/letsencrypt.sh#150]
As a nginx user I need both in the same file. It would be nice if I could just copy the whole script output to my certificate file instead of having to append the intermediate certificate manually

**Comment by lukas2511** [comment]
In normal operation this script creates `fullchain.pem` files for each certificate, containing intermediate(s) and your certificate.

**Comment by ThiefMaster** [comment]
ah, didn't know that, was always using `-s`

**Comment by lukas2511** [comment]
Yea, for the signcsr command this is actually missing, might be a good idea to add that in there too.

**Comment by nielslaukens** [comment]
I know I'm late to the party, but I object to this change.

I've specifically written the `--signcsr` command to be as simple as possible, doing only what is strictly needed. That is: get a CSR signed. If you need the certificate chain, you can get it yourself. (As the commit shows, it's only a few lines).
I need my Certificate chain in a separate file, and now I have to manually split the output again.

Or at least, make it configurable to include the full chain or not.

**Comment by lukas2511** [comment]
i changed it so now it only prints the full certificate chain if --full-chain/-fc is set
