### ISSUE TITLE
No registration exists matching provided key

### ISSUE THREAD

**Issue by abishai** [lukas2511/letsencrypt.sh#152]
I have a problem signing certificate using live CA, stage CA works. 
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for xxxxxxxxxxxxxxxxxxx...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 403)

Details:
{"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status":403}root@proxy:~ #

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Also, I copied existing letsencrypt certificate from another server and tried to renew it using this client - I've got the same error.

**Comment by abishai** [comment]
Sorry for being silly. I looked into code and deleted private_key.pem created for stage CA. Now it works.

**Comment by lukas2511** [comment]
@abishai yea this is a known issue, see #92
