### ISSUE TITLE
"keep-going" option for cron mode

### ISSUE THREAD

**Issue by BtbN** [lukas2511/letsencrypt.sh#154]
Because of the plain amount of sub-domains I am using I keep running into the rate-limit a lot of the times.
A lot of the other domains would still renew successfully, but the script in --cron mode aborts after the first cert fails to renew.

It would be extremely useful to have an option to make it continue with the other certs if one of them fails.

**Comment by lukas2511** [comment]
I think this would be great in combination with a `failed_sign` hook (open for better names), which would make things like #160 easier.

**Comment by Cyborgscode** [comment]
the "keep going" features is required for many real world situations. 

- a domain does no longer point to the server which created the cert.
the script does not know this, so it tries to renew the cert, which fails and it stops => no renew for the other domainnames.

Solution: 
1) enable dns checks for the domainnames, where the IN A has to point to an ip in the output of "ip addr" .
2) enable a admin notification emailadress to get an email if a fail on the creation or renew of a cert happens.
3) keep going with the next cert.
4) keep track of the amount of fails, incase LE has a failrate limit.

Lets be honest, your script is now in use by a lot of hosters, as it's the only easy to integrate solution on the market. You properbly will get a lot a those stability request in the near future.

**Comment by lukas2511** [comment]
@Cyborgscode

1) we may add a pre-sign hook so you can do checks in a hook before anything else happens, this won't become a part of letsencrypt itself.
2) related to #160, there will be more hooks making this easier to implement
3) yes, by now i agree that continuing would be a good idea in most cases
4) i'm not sure about this one, may be implemented at a later point
