### ISSUE TITLE
Support ECDSA ?

### ISSUE THREAD

**Issue by it-can** [lukas2511/letsencrypt.sh#158]
Letsencrypt now supports ECDSA how can I use this with your script?

https://twitter.com/letsencrypt/status/697504441075798016

**Comment by germeier** [comment]
Use the command line parameter "--algo":
./letsencrypt.sh -h | grep algo
 --algo (-a) rsa|prime256v1|secp384r1 Which public key algorithm should be used? Supported: rsa, prime256v1 and secp384r1

Or set KEY_ALGO in config.sh:
# Which public key algorithm should be used? Supported: rsa, prime256v1 and secp384r1
#KEY_ALGO=rsa

**Comment by it-can** [comment]
thanks!
