### ISSUE TITLE
Add proxy server setting

### ISSUE THREAD

**Issue by phaidros7** [lukas2511/letsencrypt.sh#161]
In certain environments a server cannot get HTTP[S] directly but only via a http_proxy. Would be nice to have a proxy seetting in /etc/letsencrypt.sh/config.sh for curl to use it :)

**Comment by lukas2511** [comment]
You should be able to just set normal proxy environment variables, curl should see and use them.

See `man curl` under "Environment".

**Comment by phaidros7** [comment]
I agree, that's the way I did it, altho it'd have been nice to have it configurable in the config :_)

**Comment by lukas2511** [comment]
@phaidros7 you can configure it in config, just use `export HTTP_PROXY=...` or whatever in config.sh, it should work
