### ISSUE TITLE
no error recover on license mismatch

### ISSUE THREAD

**Issue by ibukanov** [lukas2511/letsencrypt.sh#163]
This is similar to #2 . I am testing against own instance of boulder running at 192.168.95.14:4000. When I run `letsencrypt.sh -c` for the first time, I got an error:
```
  + ERROR: An error occurred while sending post-request to http://192.168.95.14:4000/acme/new-reg (Status 400)

Details:
{"type":"urn:acme:error:malformed","detail":"Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [http://192.168.95.14:4001/terms/v1]","status":400} 
```
After I changed the config.sh to set LICENSE to point to the test server and run letsencrypt.sh -c, I got
```
  + ERROR: An error occurred while sending post-request to http://192.168.95.14:4000/acme/new-authz (Status 403)

Details:
{"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status":403}
```

That is, there were no attempts to try to register again after the previous failed attempt. To recover I had to delete `private_key.pem`.

**Comment by lukas2511** [comment]
also slightly related to #92
