### ISSUE TITLE
unauthorized error 

### ISSUE THREAD

**Issue by RobertSchuster** [lukas2511/letsencrypt.sh#166]
After getting perfect san certifivates from the stating CA I've tried to switch to the letsencrypt productive area.
Unfortunately I'got a:
 ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 403)
followed by:
Details:
{"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status":403}

Any idea is welcome - couldn't find any help at google...

regards

**Comment by lukas2511** [comment]
duplicate, see #163 or #2 or #92 or ...

deleting account key solves the problem.

**Comment by RobertSchuster** [comment]
Hm…
How to do that?

I’ve got a valid certificate for the domain by the ACMESharp scripts for windows. Therefor I’ve thougt is has something to do with this already created registration.
Unfortunately same thing happens with an other never used togehter with letsencrypt domain.

So, please can you tell me which key ist to delete and how?

regards

Von: Lukas Schauer [mailto:notifications@github.com]
Gesendet: Samstag, 12. März 2016 23:40
An: lukas2511/letsencrypt.sh <letsencrypt.sh@noreply.github.com>
Cc: Robert Schuster <robert.schuster@compulab-consult.de>
Betreff: Re: [letsencrypt.sh] unauthorized error (#166)


Closed #166<https://github.com/lukas2511/letsencrypt.sh/issues/166>.

**Comment by RobertSchuster** [comment]
just stupid – or it was too late…
I was always looking for keys at the certs directory – deleting the private_key.pem from the base-dir it worked perfectely.


Von: Lukas Schauer [mailto:notifications@github.com]
Gesendet: Samstag, 12. März 2016 23:40
An: lukas2511/letsencrypt.sh <letsencrypt.sh@noreply.github.com>
Cc: Robert Schuster <robert.schuster@compulab-consult.de>
Betreff: Re: [letsencrypt.sh] unauthorized error (#166)


Closed #166<https://github.com/lukas2511/letsencrypt.sh/issues/166>.

**Comment by lukas2511** [comment]
@RobertSchuster great you got this solved. hoping this issue will be fully solved in the near future as from time to time a few people fall into this trap (it actually also happens to me, like all the time, only difference is that i already know how to fix it)...

**Comment by michielbdejong** [comment]
Would it be an idea to store the key in `private_key-$HASH_OF_CA_URL.json` instead of in `private_key.json`? That would resolve this confusing behavior.
