### ISSUE TITLE
more information on errors

### ISSUE THREAD

**Issue by Cyborgscode** [lukas2511/letsencrypt.sh#170]
LE JSON objects contain the real error message, which is important to fix the issue.
Unfortunatly the script does only output a generalized error msg.

any time i need to know th e real reason, i have to use "strace -s 1024 -e read  -f " to see the json result coming from the LE Server :=)

Request: add an override option for/or output the LE error msg directly

**Comment by lukas2511** [comment]
at which point do you get silent errors? on any errors i experience i always got the message printed on screen by my script, it's set up to print the full json on any hard errors

**Comment by lukas2511** [comment]
Closing this as this problem should actually be solved for quite a while now...
