### ISSUE TITLE
CONTACT_EMAIL no change in certs

### ISSUE THREAD

**Issue by pwallner** [lukas2511/letsencrypt.sh#171]
Hi,

as I unterstood, if I declare a CONTACT_EMAIL, then it should be in the certs?! If yes, in my certs the email doesn't appear. What's wrong?

Thank you,
Patrick

PS: I love your script, easy to use and fully working (except the email thing...)

**Comment by Lukas0907** [comment]
Hi,

the CONTACT_EMAIL is used for registration with the ACME server. It is used by Let's Encrypt to inform you about expiring certificates.

Cheers,

Lukas

**Comment by lukas2511** [comment]
@pwallner as @Lukas0907 said the contact email is only used for registration (and reminders from Let's Encrypt, which hasn't directly to do with this script).

i don't think it's possible to include that email in your certificate if that is what you want to know, boulder only keeps CN.
