### ISSUE TITLE
Unbound variable

### ISSUE THREAD

**Issue by eknkc** [lukas2511/letsencrypt.sh#178]
With the latest version I started receiving this error on OSX:

`./bin/le: line 27: @: unbound variable`

That line would be this:

```
_mktemp() {
  mktemp -t letsencrypt.sh-XXXXXX "${@}"
}
```

Any idea what this might be?

**Comment by eknkc** [comment]
Installed newer version of bash from homebrew and this is fixed but the default osx version is not compatible I guess.

**Comment by lukas2511** [comment]
Should be fixed now, can you check again?

**Comment by eknkc** [comment]
Fixed, thanks!
