### ISSUE TITLE
Resign certificates if (sub)domains changed

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/letsencrypt.sh#18]
Currently if you add or remove a domain from a line in domains.txt the script doesn't recognize the change and you'll just keep the existing certificate with the old set of domains. This should be improved.

**Comment by jcn** [comment]
Until this change is made, what is the recommended way of handling this manually?

**Comment by lukas2511** [comment]
For now probably the easiest way would be to just remove the symlink to the existing certificate and start the script

**Comment by lukas2511** [comment]
This is working now.
