### ISSUE TITLE
Set WELLKNOWN path per subdomain

### ISSUE THREAD

**Issue by Joery** [lukas2511/letsencrypt.sh#181]
Hi,

I'm currently running into the issue when trying to validate a domain + multiple subdomains.
The script tries to validate the acme challenge file under:

WELLKNOWN="${BASEDIR}/public_html/.acme-challenge"

Which is the challenge directory in the website root. This works for validating example.com & www.example.com, but it doesn't work for subdomain.example.com

This subdomain is located under /public_html/subdomain/

Is it possible to set up multiple WELLKNOWN paths for the different subdomains I'm trying to validate?

One of the docs recommends to set up an alias but I'm unable to modify the apache config file. Modifying this file is restricted on the server I'm running this website on.
https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/wellknown.md

**Comment by lukas2511** [comment]
Currently there is no way for a per-domain configuration of this path.

I'd suggest creating a symlink if that is possible, or create a hook script that moves the files to the correct directory using the `deploy_challenge` hook.

In the future this may change, kinda related to #105.

**Comment by Joery** [comment]
Thank you!
