### ISSUE TITLE
Can not revoke cert

### ISSUE THREAD

**Issue by bobykus** [lukas2511/letsencrypt.sh#182]
Running 

 /usr/local/sbin/letsencrypt.sh --cron --domain some.do   --challenge http-01  --config .letsencrypt/config.sh
 INFO: Using main config file .letsencrypt/config.sh
Processing  some.do
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun 27 10:11:00 2016 GMT (Longer than 14 days). Skipping renew!

While  I run 

/usr/local/sbin/letsencrypt.sh --revoke certs/some.do/fullchain-1459249840.pem  --domain some.do --challenge http-01 --config .letsencrypt/config.sh 
 INFO: Using main config file  .letsencrypt/config.sh 
Revoking certs/some.do/fullchain-1459249840.pem
 + Done.
 + Renaming certificate to    certs/some.do/fullchain-1459249840.pem-revoked

and of course then

/usr/local/sbin/letsencrypt.sh --revoke certs/some.do/fullchain-1459249840.pem-revoked  --domain some.do --challenge http-01 --config .letsencrypt/config.sh 
Revoking certs/domain.do/fullchain-1459249840.pem-revoked
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/revoke-cert (Status 409)

Details:
{"type":"urn:acme:error:malformed","detail":"Certificate already revoked","status":409}

.letsencrypt/config.sh contains 

BASEDIR=/location/some.do
WELLKNOWN="${BASEDIR}/.well-known/acme-challenge"
PRIVATE_KEY="${BASEDIR}/.letsencrypt/private_key.pem"

etc.

How come the site certificate is listed as revoked but I can not get new one because  it valid  until Jun 27?

**Comment by lukas2511** [comment]
letsencrypt.sh is looking for `cert.pem`, which still is pointing to a valid place and seems valid, it doesn't check with the server if the certificate has been revoked.

if you run the revoke command on `cert-1459249840.pem` (or just delete it, or run the command with `-x` to force renew) it should work.
