### ISSUE TITLE
change PRIVATE_KEY to ACCOUNT_KEY

### ISSUE THREAD

**Issue by reardonia** [lukas2511/letsencrypt.sh#183]
Just a recommendation:

the use of the term "PRIVATE_KEY" is overloaded; change to ACCOUNT_KEY where appropriate, avoid confusion with privkey, PRIVATE_KEY_RENEW, and the like

**Comment by lukas2511** [comment]
I agree, changed this in the mentioned commit. Thanks.

**Comment by Robby-** [comment]
How about also changing the default filenames private_key.json/pem to account_key.json/pem while at it?

**Comment by lukas2511** [comment]
@Robby- I'd like to avoid that since this would silently impact a lot of setups... :-/
