### ISSUE TITLE
Allow to use comments in the domains.txt file

### ISSUE THREAD

**Issue by Robby-** [lukas2511/letsencrypt.sh#187]
It would be nice to be able to put comments in the domains.txt file. For example if some domain needs a note or something, or to quickly disable a domain by commenting it out and not having to entirely remove it from the file.

**Comment by lukas2511** [comment]
You should be able to use `#` at the beginning of a line to start a comment:

```
# cool domains
example.org www.example.org
# example.net www.example.net
```

**Comment by Robby-** [comment]
Oh. I didn't try it because I didn't saw that mentioned, and from a quick glance at the script I didn't think it was possible, that's what I get for making assumptions. ;)

Thank you.
