### ISSUE TITLE
Feature Request: tell the status of the request, instead of just invalid

### ISSUE THREAD

**Issue by Cyborgscode** [lukas2511/letsencrypt.sh#189]
This the the json that came back from LE: 

{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/7ftGAV2gxxWnohIAl_Aq60JWZOSNhuR_4rQH5bRpUEA/74809467","token":"bDZxoGLIuz28jHDH0Ga5nDQ-erAKfXdUW9WWKeWLSd8","keyAuthorization":"bDZxoGLIuz28jHDH0Ga5nDQ-erAKfXdUW9WWKeWLSd8.e5FZjrnwb1SZURXTovcByAXqtydN8vSfcQLBNTs0yiM"}

The script says invalid : 

+ Challenge is invalid! (returned: invalid)

But it's not invalid, it's just stuck on LE's side ( we have an issue open there for the domain in question )

**Comment by lukas2511** [comment]
Did you check if you are running an old version of the script? The output on errors should be similar to `Challenge is invalid! (returned: invalid) (result: [...]json here[...])`.

Also "returned: invalid" actually gets parsed from the json response, it's impossible for the script to just invent a status "invalid" at that point. As long as the status is "pending" it tries again and again until it's no longer "pending".

Closing this bug as it doesn't seem like an actual bug in the script.
