### ISSUE TITLE
Certificate revocation

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/letsencrypt.sh#19]
Revocation of certificates would be a really nice feature to have.

**Comment by germeier** [comment]
I agree!

The protocol spec for "Certificate Revocation" looks straight forward. Anyone who is eager to implement this feature? Otherwise I would give it a try...

**Comment by lukas2511** [comment]
@germeier If you want you can give it a try, shouldn't be too hard.

**Comment by lukas2511** [comment]
implemented with #21 in 063d28a6dcc755d339b05cb55880347a8c6c7b4a
