### ISSUE TITLE
Any chance to support namecheap DNS server hooking

### ISSUE THREAD

**Issue by 556556bt** [lukas2511/letsencrypt.sh#191]
My domains currently parked at namecheap name server. I wanna to use DNS-01 challenge to renew certificate. However, i see no namecheap support in the hook list. What else I can do to have automatic operation?

**Comment by lukas2511** [comment]
Write your own hook? If they have an API it shouldn't be too hard.

The hook system is meant to be written by others so letsencrypt.sh can become compatible with a whole lot of custom setups, I didn't write any of those hook scripts mentioned in the wiki.

**Comment by samtombson** [comment]
https://github.com/samtombson/letsencrypt/blob/master/namecheap_dns_api_hook.sh

**Comment by bviktor** [comment]
Thanks, are you willing to add this to the [DNS hook list](https://github.com/lukas2511/letsencrypt.sh/wiki/Examples-for-DNS-01-hooks), @samtombson ?

**Comment by samtombson** [comment]
@bviktor Sure, I willing.
