### ISSUE TITLE
Getting a traceback error

### ISSUE THREAD

**Issue by GTAXL** [lukas2511/letsencrypt.sh#194]
[root@excession:letsencrypt.sh]./letsencrypt.sh -c -d excession.gtaxl.net -d irc.gtaxl.net -t dns-01 -k 'hooks/cloudflare/hook.py'
# INFO: Using main config file /root/letsencrypt.sh/config.sh
+ Generating account key...
+ Registering account key with letsencrypt...
Processing excession.gtaxl.net with alternative names: irc.gtaxl.net
 + Signing domains...
 + Creating new directory /root/letsencrypt.sh/certs/excession.gtaxl.net ...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for excession.gtaxl.net...
 + Requesting challenge for irc.gtaxl.net...
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 14, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax

I'm on Debian 8.4. Please help :(

**Comment by GTAXL** [comment]
I have no idea why Github formatted it like that, sorry.

**Comment by rumpelsepp** [comment]
Use three backticks: 

```
hans
```

**Comment by lukas2511** [comment]
This is a problem with your hook script and not with letsencrypt.sh. I don't maintain any hook scripts.
