### ISSUE TITLE
pre-hook & post-hook

### ISSUE THREAD

**Issue by verwilst** [lukas2511/letsencrypt.sh#196]
Instead of a simple --hook, it would be nice to have a --pre-hook and --post-hook, so we can do cleanups afterwards.

**Comment by lukas2511** [comment]
The hook script gets called with a parameter which tells it what to do, see https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/examples/hook.sh.example.

With that I don't see any reason why to make this script more complicated with dozens of hook parameters for any case where a hook could be called.

**Comment by verwilst** [comment]
Ok, let's store this in the brainfart section. :-) Doh!
