### ISSUE TITLE
Lighttpd (and some other apps) requires both cert and privkey to be in the same .pem file

### ISSUE THREAD

**Issue by the-vindicar** [lukas2511/letsencrypt.sh#197]
Could this be made an option?
Or, if it can be done with hook, can you add a doc entry regarding how to do it?

**Comment by lukas2511** [comment]
I don't want any more formats of keys and certs so this would have to be done with a hook script.

In theory something like this should work (untested):

```
#!/usr/bin/env bash

function deploy_cert {
    local DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" FULLCHAINFILE="${4}" CHAINFILE="${5}" TIMESTAMP="${6}"

    cat "${KEYFILE}" "${FULLCHAINFILE}" > "${BASEDIR}/certs/${DOMAIN}/combined.pem"
}
```

**Comment by domenpk** [comment]
Hook should actually contain CERTFILE instead of FULLCHAINFILE:

```
    echo " + HOOK: Merging KEYFILE and CERTFILE to ssl.pem"
    umask 0077
    cat "${KEYFILE}" "${CERTFILE}" > "${BASEDIR}/certs/${DOMAIN}/ssl.pem"
```

Btw.

**Comment by lukas2511** [comment]
@domenpk and then you are missing the chain certificates, which are important too ¯\_(ツ)_/¯

**Comment by domenpk** [comment]
Ah, no, no... Lighttpd has 2 config options `ssl.pemfile` and `ssl.ca-file`. Former should contain both KEYFILE and CERTFILE, latter is FULLCHAINFILE.

**Comment by lukas2511** [comment]
Interesting... don't even want to know how it came to this.

Anyway, with hooks this can easily be done :)

**Comment by the-vindicar** [comment]
Using the hook method now and it works fine, thanks!
However, you might still want to add this use-case to documentation, for googlers' sake.
