### ISSUE TITLE
DNS-01 hook for Azure

### ISSUE THREAD

**Issue by bviktor** [lukas2511/letsencrypt.sh#198]
Hi, I have permissions to edit the wiki page but I thought I'd ask first. Is it possible to add my hook to the list? It allows for manipulating Azure DNS records for certificates.

Here it is:

[Certzure](https://github.com/bviktor/certzure)

Thanks in advance.

**Comment by lukas2511** [comment]
Hey, yes sure, in the current state the wiki is meant to be open for everybody, go ahead and add your hook script!

**Comment by bviktor** [comment]
Thanks, Lukas!
