### ISSUE TITLE
mixed challenges for one certificate

### ISSUE THREAD

**Issue by ma0am** [lukas2511/letsencrypt.sh#199]
is it possible to extend the domain.txt config for using different challenges for each host?
aka i need to use dns-01 challenges for roundrobins and http-01 for some external domains
(host challenges for roundrobins are hard to deploy, 
but dns access to external domains is not possible)

here is an example for an **example.com certificate** which i would like to build:

http-01 challenges for:
- example.com
- www.example.com
- host.example.com
- host.otherdomain.com

dns-01 challenges for:
- roundrobin.example.com
- more.roundrobin.example.com

**Comment by lukas2511** [comment]
Not yet, sorry. The idea to have per-domain settings has been around for a while (see #105), but it hasn't been implemented yet.

Workaround for now would be to do something like `./letsencrypt.sh -c -t dns-01 -d roundrobin.example.com -d more.roundrobin.example.com`. 
This would have the same effect as if you'd have a line `roundrobin.example.com more.roundrobin.example.com` in domains.txt and dns-01 set in config.sh.
