### ISSUE TITLE
Error when requesting ceritficate...

### ISSUE THREAD

**Issue by taylorotwell** [lukas2511/letsencrypt.sh#2]
When requesting a certificate for a domain... I get through all steps successfully, even challenges; however, I get a curl error when requesting the actual certificate:

```
  + Requesting certificate...
curl: (22) The requested URL returned error: 403 Forbidden
  + Done!
```

**Comment by taylorotwell** [comment]
Also curious how to use the staging setup for LetsEncrypt so I can issue test certificates. Changing the CA to the typical "https://acme-staging.api.letsencrypt.org/directory" I use with the official LetsEncrypt client results in 404s.

**Comment by lukas2511** [comment]
Yea this still is missing some error handling.
To use the staging environment you should set the CA to "https://acme-staging.api.letsencrypt.org", without the "/directory" at the end, it should work.

**Comment by taylorotwell** [comment]
Yeah I gave that shot when I was experimenting and that turned the 404 into a 403 Forbidden:

```
  + Generating private key...
  + Generating signing request...
  + Requesting challenge for verbler.com...
curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by lukas2511** [comment]
I'm not sure what's going on there, maybe it requires the usage of a different agreement url on registration.

**Comment by taylorotwell** [comment]
Error after latest commits with `https://acme-staging.api.letsencrypt.org` as CA

```
  + Requesting challenge for verbler.com...
  + ERROR: An error occured while sending post-request to https://acme-staging.api.letsencrypt.org/acme/new-authz (curl: (22) The requested URL returned error: 403 Forbidden)
```

**Comment by taylorotwell** [comment]
Is there a way for me to receive the full error response body? Would that contain anymore info?

**Comment by taylorotwell** [comment]
Modified the script a bit and got the real error:

  + Error: Can't retrieve challenges ({"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status":403})

**Comment by taylorotwell** [comment]
Resolved by deleting my privatekey.pem and letting it regenerate.

**Comment by connaryscott** [comment]
I am stuck here here as well.

```{"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status":403}
```

Continually got this error until i ran it with just -c, then I got:
Then i got this:

```
{"type":"urn:acme:error:malformed","detail":"Provided agreement URL [https://testca.kurz.pw/terms/v1] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf]","status":400}
```

After setting my LICENSE to that value, which was a complete guess on my part, i then got that same 403 error....

**Comment by connaryscott** [comment]
I was able to get around it by just using the -c option and removing my private key which I believe others did as well.  I am moving forward now.

**Comment by sztyler** [comment]
Is there any solution to use my one private key? -Its really annoying -I _have to_ use one of my private keys due to HPKP otherwise I cannot switch my certificate....
