### ISSUE TITLE
New Key in place even if renewal failed

### ISSUE THREAD

**Issue by meinname** [lukas2511/letsencrypt.sh#20]
Hi, 
as far as i can see from the code it can happen that if "PRIVATE_KEY_RENEW = yes" a new key is generated and activated - even if we are not sure if a new certificate was issued.

Maybe the removal of the softlink an relinking should be done after the matching cert was issued.

**Comment by lukas2511** [comment]
Should be fixed in f343dc11e82760b741676b57de59f46b8b25ac78
