### ISSUE TITLE
While domain is not registered, letsencrypt.sh returns no error 

### ISSUE THREAD

**Issue by bobykus** [lukas2511/letsencrypt.sh#207]
Seems letsencrypt behavior changed recently. Using your tool 

_/usr/local/sbin/letsencrypt.sh --cron --domain some.pl --domain www.some.pl --challenge http-01 --config .../some.pl.dk/.letsencrypt/config.sh_

were getting 

_ERROR: Challenge is invalid! (returned: invalid) (result: {"type":"http-01","status":"invalid","error":{"type":"urn:acme:error:connection","detail":"DNS problem: NXDOMAIN looking up A for some.pl"},"uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/yx4xQiXuFusLu-MFtAnUFXcBxoIqWWImKq05mNdS0Uw/90567863","token":"hT5T7cDEGdnt4UvHPR4jFkt1C9kU4uoMau3hsp9BxZ4","keyAuthorization":"hT5T7cDEGdnt4UvHPR4jFkt1C9kU4uoMau3hsp9BxZ4.6KqDpmIgUn413LbT6leEv1TfILZqkDmTU7_fuM25T5I","validationRecord":[{"url":"http://some.pl/.well-known/acme-challenge/hT5T7cDEGdnt4UvHPR4jFkt1C9kU4uoMau3hsp9BxZ4","hostname":"some.pl","port":"80","addressesResolved":null,"addressUsed":""}]})_

from Fri May 20 20:50:10 CEST 2016 I getting  only 

_+ Requesting challenge for some.pl..._

and then no thing, no error!
Please mind  some.pl or whatever is not registered, so ERROR was correct output. 
The problem is no output at all since  Fi May 20 night.

**Comment by lukas2511** [comment]
This is not a problem with this script.

`DNS problem: NXDOMAIN looking up A for some.pl`: letsencrypt can't resolve your domain name and can't access your page for receiving the challenge response

**Comment by bobykus** [comment]
No, I think your script works perfect. I just trying to say letsencrypt site returns no error or different  looked message while error happens. It seems to be changed last Friday. Just FYI.

**Comment by lukas2511** [comment]
Do you have the newest version of this script? There have been important changes.

**Comment by bobykus** [comment]
No, but I will try.

**Comment by bobykus** [comment]
It looks very nice now - response  contains much more readable info. Thank you so much!
