### ISSUE TITLE
a hook that is executed once per run

### ISSUE THREAD

**Issue by MichaelKunze** [lukas2511/letsencrypt.sh#209]
Hello there!

I have the following setup:
* 10 different certificates for nginx vhosts
* 1 cert for incoming mail server
* 1 cert for outgoing mail server

What i want to archive is to restart nginx only once when any of the 10 vhost certificates have been renewed. I'm already using the hooks that are present in the example directory but that function would be called for each certificate (so 10 times in worse case) which would mean 10 nginx restarts within a single letsencrypt.sh run.
Is there any existing feature i can use to reach my goal?

Thanks in advance,
Michael

**Comment by Rayne** [comment]
Side note: You could also reload the configuration instead of restarting the webserver.

**Comment by lukas2511** [comment]
This is planned, see discussion for #148
