### ISSUE TITLE
json response issue

### ISSUE THREAD

**Issue by connaryscott** [lukas2511/letsencrypt.sh#213]
We are using  your client in our TLS automation, on line #426 the following change was made since this client just began to fail on 26 May 2016:

```
+    #challenges="$(printf '%s\n' "${response}" | sed -n 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/p')"
+    challenges="$(printf '%s\n' "${response}" | tr -d '\n' |sed -n 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/p')"
```

Notice that we needed to delete all newlines in the json response.  Perhaps the response is now pretty format as opposed to a single line?

**Comment by lukas2511** [comment]
You also could just have downloaded the newest version which also includes a similar change. Thanks anyway.

**Comment by connaryscott** [comment]
ok thanks did not realize that.  appreciate the response.
