### ISSUE TITLE
characters getting replaced

### ISSUE THREAD

**Issue by Kufi-Ism** [lukas2511/letsencrypt.sh#221]
Hi,

found a issue while playing around with your script. Seems all u in domains names getting replaced by l regardless if the chars are in the domains.txt or manually entered by -d.

Some Sample output:
admin@FileStore:/share/homes/Stefan/letsencrypt.sh$ ./letsencrypt.sh -c -d uuuu.uu
INFO: Using main config file /share/homes/Stefan/letsencrypt.sh/config
Processing llll.ll
 + Signing domains...
 + Creating new directory /share/MD0_DATA/homes/Stefan/letsencrypt.sh/certs/llll.ll ...
 + Generating private key...

with domains.txt
 ./letsencrypt.sh -c 
INFO: Using main config file /share/homes/Stefan/letsencrypt.sh/config
Processing test-ll.de
 + Signing domains...
 + Creating new directory /share/MD0_DATA/homes/Stefan/letsencrypt.sh/certs/test-ll.de ...
 + Generating private key...
Domains looks like this:
admin@FileStore:/share/homes/Stefan/letsencrypt.sh$ cat domains.txt 
test-uu.de

I am using the script on a QNAP NAS system but this should not have any influence on the script.

**Comment by lukas2511** [comment]
This probably has something to do with `tr '[:upper:]' '[:lower:]'` which should convert all domain names to lowercase letters. Can you tell me what version of `tr` QNAP is using?

**Comment by Kufi-Ism** [comment]
Hi,
Qnaps QTS Issing a busybox version of tr:
BusyBox v1.01 (2016.03.10-19:14+0000) multi-call binary

Usage: tr [-cds] STRING1 [STRING2]

Translate, squeeze, and/or delete characters from
standard input, writing to standard output.

Options:
        -c      take complement of STRING1
        -d      delete input characters coded STRING1
        -s      squeeze multiple output characters of STRING2 into one character

**Comment by lukas2511** [comment]
Well I don't really support busybox binaries as they are lacking a lot of features, that should be the problem.
