### ISSUE TITLE
http-01-port support

### ISSUE THREAD

**Issue by leleobhz** [lukas2511/letsencrypt.sh#227]
Hello!

Its possible to support http-01-port protocol to allow non-80 port to be checked?

LetsEncrypt official client support change http port via this parameter (Documentend in http://letsencrypt.readthedocs.io/en/latest/using.html )

Thanks!

**Comment by lukas2511** [comment]
Port options are listed under "The following flags are meant for testing purposes only!", I think this only works with specially configured boulder instances and not with anything official. If somebody needs this for testing purposes i'd accept a pull request.
