### ISSUE TITLE
Clean old certificate files

### ISSUE THREAD

**Issue by jsmad** [lukas2511/letsencrypt.sh#229]
I've been running this nice script for some time now and I've noticed that my CERTDIR is filling up with old and expired certificate files. For example, one of my servers already has more than 320 expired certificate files (csr/pem combos).

Should this script be responsible for cleaning up those expired certificates, or do you think we should write our own thing to clean them up?

I'd appreciate your thoughts.

Thank you.

**Comment by seefood** [comment]
I personally would not want the script to clean this up by default. also, it's a one-line cron job to clean this up (or in a hook), so it's better to separate this functionality (per the Unix doctrine).

**Comment by lukas2511** [comment]
` --cleanup (-gc)                  Move unused certificate files to archive directory`
