### ISSUE TITLE
Add per-domain configuration files

### ISSUE THREAD

**Issue by leonklingele** [lukas2511/letsencrypt.sh#233]
It would be useful to be able to have different configuration files per domain(s).
Example use case:
Not all of my domains should use OCSP Must-Staple, but I still want to use the `--cron` flag for auto-renewal.

**Comment by lukas2511** [comment]
https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/per-certificate-config.md

**Comment by leonklingele** [comment]
Whoops. Nice & thank you 😃
