### ISSUE TITLE
registration_info not generated

### ISSUE THREAD

**Issue by mosandlt** [lukas2511/letsencrypt.sh#235]
The registration_info.json get not generated anymore

**Comment by lukas2511** [comment]
Should be next to the private key in the accounts directory.

**Comment by mosandlt** [comment]
not right.. you do nothing in your script to create this file

**Comment by lukas2511** [comment]
https://github.com/lukas2511/letsencrypt.sh/blob/master/letsencrypt.sh#L242-L246

**Comment by mosandlt** [comment]
okay sorry. strange. i see only my key and no json file.

**Comment by lukas2511** [comment]
Please keep in mind that the json file only gets generated on registration. If you already had an account key it can't generate the json file.
