### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by jult** [lukas2511/letsencrypt.sh#240]
OK, this issue is completely obsolete, as far as I'm concerned. Turned out there was a default python exclusion set in yum.conf, which is strangely never even echoed to its user, not even when doing "yum install python" or something. Seriously hating yum now.

**Comment by seefood** [comment]
Have you read the readme, at least once?

**Comment by extremeshok** [comment]
lol, that would be too much effort ;-P

Sorry, I could not resist the trolling

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by jult** [comment]
What do you mean by "the readme" ? And yes, I read it all. It's unclear where which files need to be changed. You just have not documented anything pointing to that.

**Comment by jult** [comment]
"Generally you want to set up your WELLKNOWN path first," where? I see it in your docs folder, but it does not even state that a filename needs to be changed, or moved, or whereto. You assume a lot, you seriously do.

**Comment by jult** [comment]
I do a git clone of your stuff, as recommended elsewhere, and on the server I see the git formatting in all files, which is also not very appropriate. I mean, if you do make txt files, make them in the .txt format, i.e. don't use code tags. I would easily have created a file like this:

domains.txt (of which still unclear where to put it):
```
```text
example.com www.example.com
example.net www.example.net wiki.example.net
```

```

**Comment by jult** [comment]
"An example would be to create a directory /var/www/letsencrypt and set WELLKNOWN=/var/www/letsencrypt in the scripts config."

What config? The only config after a git clone I see is under /.git/, but that's not "the script config".

**Comment by germeier** [comment]
There are three things that are assumed:
1. That you can read the and understand the first page completey "For getting started I recommend taking a look at docs/domains_txt.md, docs/wellknown.md and the Usage section on this page"
2. That you are not to shy to actually read these documents.
3. That you are able to find and read: https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/examples/config

**Comment by jult** [comment]
Like I wrote, and I know startssl is in the news because of their bad [attempts at trying to go the letsencrypt route](https://www.computest.nl/blog/startencrypt-considered-harmful-today/), but this is not the what would be expected for letsencrypt usage. The directory structure is not even like the one letsencrypt uses by default through the python installs of certs in /etc/letsencrypt, which is also confusing, since that is the logical route to follow, I would say. But hey, that's me. And even acmetool decided to not follow up on that logic. You're a bunch of weird coders, if you ask me.

The thing is; I have to install a cert on a CentOS 6.8 server (not mine, and I can't upgrade it), acmetool would not work, because install from source requires at least a GLIBC version that I could not get installed on CentOS 6.7, and acmetool provides no package for CentOS 6.* (even though they weirdly do provide the repo for it that, without documenting it, just doesn't hold acmetool).
Yes, one could try python 2.7 on CentOS 6.8, but whatever I do, I keep running into issues with that, a can of worms would be an understatement at this point.
```
# yum --enablerepo=ius install git python27 python27-devel python27-pip python27-setuptools python27-virtualenv
Loaded plugins: fastestmirror, presto, priorities
Setting up Install Process
Loading mirror speeds from cached hostfile
* base: mirrors.supportex.net
* epel: mirror.nl.leaseweb.net
* extras: mirror.1000mbps.com
* ius: mirror.amsiohosting.net
* updates: mirrors.supportex.net
ius | 2.2 kB 00:00
ius/primary_db | 202 kB 00:00
10 packages excluded due to repository priority protections
Package git-1.7.1-4.el6_7.1.x86_64 already installed and latest version
No package python27 available.
No package python27-devel available.
No package python27-pip available.
No package python27-setuptools available.
No package python27-virtualenv available.
Nothing to do
```

So I end up with this shell script option, which, one must admit, requires time to get running that is presumably more than installing through startssl. Which was my earlier point.

**Comment by germeier** [comment]
If letsencrypt.sh is to complicated for you, you can always go the startssl route or simply use another lightweight ACME implementation, see: https://github.com/certbot/certbot/wiki/Links

**Comment by lingej** [comment]
this is not letsencrypt! Its the letsencrypt.sh repository

**Comment by jult** [comment]
I know, but why completely change the way they prefer to do things (and why install certs in some weird /opt/letsencrypt.sh/certs dir)? You use their servers, you could at least use their conventions. Unless it's something you like to do, to confuse the public at large.

Also, I'm just guessing, but this script wants us to change file.extension.md into file.extension or what? And then move them to the folder where the .sh is.

**Comment by germeier** [comment]
> Also, I'm just guessing, but this script wants us to change file.extension.md into file.extension or what? And then move them to the folder where the .sh is.

I give up!

**Comment by seefood** [comment]
@jult I actually find the original LetsEncrypt tool to completely change the way I like to do things, including attempting to reconfigure the webserver(s) for me, pick directories for me, and then refuse to run under cron anything is bothering it (and it's a highly sensitive primadonna).

Here, I just:

- git-cloned it into a directory,
- created the config and domains list,
- made a common acme directory,
- made sure all the apache and nginx vhosts show that directory at the correct URL (I just include the same file again and again in all the vhosts' configs)

and that should do it. This works well since I have a mix of static, php and other sites all on the same machine, in various directories owned by different users, and this client just works and allows me to never worry about expired certificates ever again.

If this is not your bag, feel free to use any of the other dozen or two clients written to use their server. this client though, is as simple as they get.

**Comment by jult** [comment]
Again, must be me, but is this .md extension something I should know about? First time I encounter it..

**Comment by germeier** [comment]
http://lmgtfy.com/?q=extension+md

**Comment by Rayne** [comment]
> Again, must be me, but is this .md extension something I should know about? First time I encounter it..

Your `nginx-config` (`jult/nginx-config`) repository consists of two files and one of them is a `README.md` with valid Markdown. Please stop trolling.

**Comment by jult** [comment]
On July 6, 2016 6:25:19 PM GMT+02:00, Dennis Meckel <notifications@github.com> wrote:
> > Again, must be me, but is this .md extension something I should know
> about? First time I encounter it..
> 
> Your `nginx-config` (`jult/nginx-config`) repository consists of two
> files and one of them is a `README.md` with valid Markdown. Please
> stop trolling.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lukas2511/letsencrypt.sh/issues/240#issuecomment-230826561

It was forked, I never wrote it. It's not my Nginx config. 
-- 
Sent from my OpenPDroid protected phone with k9mail. Please excuse my brevity.

**Comment by rumpelsepp** [comment]
@lukas2511 Please lock this. It is spaming my inbox.
