### ISSUE TITLE
Update license agreement (due at August 1st)

### ISSUE THREAD

**Issue by leonklingele** [lukas2511/letsencrypt.sh#243]
```
Let's Encrypt Subscriber,
We're writing to let you know that we're updating the Let's Encrypt Subscriber Agreement
effective August 1, 2016. You can find the updated agreement (v1.1.1) as well as the
current agreement (v1.0.1) in the "Let's Encrypt Subscriber Agreement" section of the
following page: https://letsencrypt.org/repository/
```
Old: https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf
New: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf

What happens if one does not update letsencrypt.sh to post the new LA? Does the signing process fail?

**Comment by germeier** [comment]
https://community.letsencrypt.org/t/lets-encrypt-subscriber-agreement-v1-1-1/17409/7

**Comment by lukas2511** [comment]
Interesting thing is that I can't yet push an update with the new agreement as boulder doesn't accept a registration with that url... Also this will lead to another wave of stupid issues "letsencrypt.sh is not working" "did you try updating?" "oh now it works"... meh.

**Comment by shoeper** [comment]
https://community.letsencrypt.org/t/lets-encrypt-subscriber-agreement-v1-1-1/17409/7
