### ISSUE TITLE
Agreement URL is out of date

### ISSUE THREAD

**Issue by rmclain** [lukas2511/letsencrypt.sh#248]
Response:

  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]"

**Comment by lukas2511** [comment]
Yup, I just pushed the commit updating the license agreement, should work now.

**Comment by rmclain** [comment]
Thank you!
