### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by glensc** [lukas2511/letsencrypt.sh#252]
please make new release ASAP, since the old release contains old license url and client fails to work

```
# /usr/sbin/letsencrypt.sh -c
# INFO: Using main config file /etc/webapps/letsencrypt.sh/config.sh
+ Generating account key...
+ Registering account key with letsencrypt...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-reg (Status 400)

Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]",
  "status": 400
}
```

it's fixed in master: afabfff06e2dece1772ed788ac41ca0d297ab49b
so just new release is needed!

**Comment by lukas2511** [comment]
There are still a few things that I see as important for the next release, so... sorry, but this has to wait. Packagers can cherrypick this commit and most people use a fixed commit id or just master anyway.
