### ISSUE TITLE
What is the relationship between this repo and certbot? 

### ISSUE THREAD

**Issue by zfrenchee** [lukas2511/letsencrypt.sh#258]
@lukas2511 It seems like this repo doesn't depend on certbot at all. Do they do the same thing? Do they do very different things? (Sorry I'm a noob! It would be nice if certbot were mentioned in the readme though, for fellow noobs)

**Comment by EvilJordan** [comment]
This is a great question. I don't know the definitive answer, but from my experimentation, this repo is more of a manual, stripped-down, essentials version (and works really well). I have been able to create tens of dozens of certs for sites quickly and easily with this repo, and setting up a cron job for auto-renew is dead-simple.

Certbot didn't work for me on my non-standard system, seemed bloated, and I found the documentation to be super-unclear, like it was geared towards total beginners, but even then lacked clarity on what was going on.

**Comment by seefood** [comment]
@EvilJordan is correct. The Let's Encrypt system is using a protocol they call "ACME". Like everything else in computers, there's more than one way to implement it. certbot is the default/reference implementation, this repo is a simpler, clearer tool implementing it all in bash. It may not have all the same features (like setting up a temp webserver on port 80), but all the other important features are there, with a clear way of adding the missing ones with the webhooks.

if the ACME protocol gets an update,  both certbot and letsencrypt will get an upgrade, but that's the only relationship between the two :)
