### ISSUE TITLE
Tag v0.2.1 and update CHANGELOG

### ISSUE THREAD

**Issue by jjmata** [lukas2511/letsencrypt.sh#267]
So people can pull from here confidently ... working on a PR as we speak.

Currently the license agreement check fails.

**Comment by lukas2511** [comment]
Meh. Okay. Was hoping to get some stuff done before the next release but I see that it's taking too long... Open a PR, I'll merge it.

**Comment by jjmata** [comment]
I don't think I can tag via PR anyway, and all I would do is edit the CHANGELOG to include everything change thus far (which I'm not sure I want to do not knowing the state of affairs ...)

Your call.  I've forked already so I'm cool with it either way.  Thanks for putting this together, BTW! :+1:
