### ISSUE TITLE
Add lockfile

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/letsencrypt.sh#31]
If this script is used inside a cronjob it may interfere with a user using the script, so i think it would be a good idea to have some sort of lock-file to make sure it's at least not signing the same domain at the same time, or maybe even that it's not running at the same time.

**Comment by alexandresobolevski** [comment]
Hi @lukas2511 . Could I ask you to elaborate on what exactly is protected. My situation is that I wish the script to be accessible asynchronously to renew certificates of some of my domains. It will be accessed from different processes - possibly at the same time but renewals are performed for different domains. What are the repercussions if I use the `no-lock` argument?
Thanks a lot.

**Comment by lukas2511** [comment]
@alexandresobolevski sorry for the late response: locking basically protects the script to write to the same files at the same time. if you register an account key first and control the script externally later on using the `-d domain.tld -d www.domain.tld` options there shouldn't be any remaining conflicts, but you should never use the no-lock option when running with a domains.txt
