### ISSUE TITLE
RFC: domains.txt format

### ISSUE THREAD

**Issue by LynxChaus** [lukas2511/letsencrypt.sh#34]
It's possible to change domains.txt format to include webroot type domain aliases?
i.e.
/var/www/example.org/ apache example.org www.example.org
/var/www/example.net/ nginx example.net www.example.net other.example.net
/var/www/common/  mail mailhost.example.org webmail.example.org

and modify hook calling to pass webroot and type to it.

**Comment by lukas2511** [comment]
I like the idea, but i don't like the format.

Maybe something more like this which allows those parameters to be optional:

```
example.org www.example.org WEBROOT=/var/www/example.org USERINFO=apache
example.net www.example.net WEBROOT=/var/www/example.net
example.mx www.example.mx USERINFO=mail
example.com www.example.com
```

But maybe someone has an even better idea...

**Comment by M-M-M-M** [comment]
I like the format of optional parameter PARAMETER=value

And passing these parameters as environment variables to hook script will be great and avoiding to surcharging hook parameter command line.

**Comment by LynxChaus** [comment]
Add minimal parser https://github.com/LynxChaus/letsencrypt.sh/commit/a0e62a4bcabe30e976b72e97898bbbd2baf62761

Any suggestion?

**Comment by lukas2511** [comment]
@LynxChaus from reading your parser it looks like it just supports things like `VAR=value`, but i'd like to also see support for `VAR="value value value"` and/or escaped values like `VAR=value\ value\ value`.
I think splitting the line at the right point and just passing it through declare would solve this.

**Comment by lukas2511** [comment]
This actually could be replaced by putting extra config files into the certificates directory. This may actually also be useful for storing per-certificate options like RENEW_DAYS and PRIVATE_KEY_RENEW. That would make this a lot easier to implement and it wouldn't have the whitespace issue.

**Comment by lukas2511** [comment]
Closing this, see #105 for a replacement for this.
