### ISSUE TITLE
Certificate invalid?

### ISSUE THREAD

**Issue by taylorotwell** [lukas2511/letsencrypt.sh#4]
Once I get a certificate using the production LetsEncrypt CA, the certificate doesn't seem valid and doesn't seem complete. For example, here is one I just created:

```
-----BEGIN CERTIFICATE-----
eyJ0eXBlIjoidXJuOmFjbWU6ZXJyb3I6dW5hdXRob3JpemVkIiwiZGV0YWlsIjoi
RXJyb3IgY3JlYXRpbmcgbmV3IGNlcnQgOjogQXV0aG9yaXphdGlvbnMgZm9yIHRo
ZXNlIG5hbWVzIG5vdCBmb3VuZCBvciBleHBpcmVkOiB2ZXJibGVyLmNvbSB3d3cu
dmVyYmxlci5jb20iLCJzdGF0dXMiOjQwM30=
-----END CERTIFICATE-----
```

Am I supposed to be doing something else with the final `cert.pem` file once I the script finishes to make it a valid certificate?

**Comment by lukas2511** [comment]
This is an error message encoded in base64 m)

"{"type":"urn:acme:error:unauthorized","detail":"Error creating new cert :: Authorizations for these names not found or expired: verbler.com www.verbler.com","status":403}"

I think this has to do with issue #3, i'll fix that now.

**Comment by lukas2511** [comment]
Mh no actually this should work. I don't know what is going on here.

**Comment by lukas2511** [comment]
Should work now.

**Comment by taylorotwell** [comment]
Ah OK, is it possible to error out if we get a base64 encoded error message? I recently ran into another one where I had hit the production limit for a domain name and got the base64 encoded error message in the "certificate" file...

**Comment by lukas2511** [comment]
I'm still working on error handling, so yea at some point this will be detected.

**Comment by rudis** [comment]
Error handling should be good enough now to handle all error messages from ACME.
