### ISSUE TITLE
shasum: command not found

### ISSUE THREAD

**Issue by ik0** [lukas2511/letsencrypt.sh#42]
Hello,

I use your script on old gentoo instalation and get this error:
./letsencrypt.sh: line 135: shasum: command not found

So i've just changed "shasum -a 256" to "sha256sum" and it works ! I know I use very old instalation, but that's why I don't/can't use official letsencrypt client.

**Comment by martinvolf** [comment]
Or you can create a script called shasum in /usr/bin or /usr/local/bin with this in it:
```shell
#!/bin/bash
shift 2
sha256sum $@
```
M.

**Comment by ik0** [comment]
I think shasum comes from Perl and if author want this project to be perl independent this should be changed.

**Comment by martinvolf** [comment]
You are right. And "sha256sum" is shorter ;-)

**Comment by lukas2511** [comment]
Just to clarify: I was using shasum because sha256sum doesn't seem to be available on bsd systems. Now i switched it to use openssl for generating the hash, which hopefully works everywhere.
