### ISSUE TITLE
hostname regex seems to be wrong

### ISSUE THREAD

**Issue by jollyjinx** [lukas2511/letsencrypt.sh#45]
Currently the regex for hostnames seems to be incorrectly escaped as hostnames like smokeping.example.com are incorrectly parsed.
I've doubled escaped the:

sed 's/^\\s*//g;s/\\s*$//g' 

to:

sed 's/^\\\\s*//g;s/\\\\s*$//g'

and now it works for me.

**Comment by lukas2511** [comment]
Mh... tiny problem with this: BSD version of sed behaves different than GNU version...
The original line worked fine with GNU sed but had problems with BSD sed,
the "fixed" line is exactly the other way round...
Need to find a solution for this :-/

**Comment by lukas2511** [comment]
Oops well actually, the "fixed" version actually just doesn't work at all, it doesn't remove the whitespace, it just passes the line as is.
