### ISSUE TITLE
RFE: domains.txt.d

### ISSUE THREAD

**Issue by dehnhard** [lukas2511/letsencrypt.sh#46]
For integrating this script into a webserver with several seperated vhosts it would be great if it could gather the domain info also from files in a directory named domains.txt.d (if it exists). It would function like any other *.d config directory, i.e. concatenating all files with suffix txt.

**Comment by lukas2511** [comment]
The parsing of domains.txt is ugly enough as it is right now, and you can implement that behaviour for yourself by using the command-line options of the script (passing domain names with `--domain "example.com www.example.com")`.
