### ISSUE TITLE
permissions of ${WELLKNOWN}

### ISSUE THREAD

**Issue by martinvolf** [lukas2511/letsencrypt.sh#48]
When letsencrypt.sh creates ${WELLKNOWN}, it should probably `chmod 0711` it, otherwise it has 0700 mode.

**Comment by ik0** [comment]
+1
nginx can't read it and return "Permission denied", so challenge is invalid.

**Comment by lukas2511** [comment]
i kinda fixed this by removing the functionality to automatically create the directory in 5a29d1853efcfda2e3880f8a5a56931701a1ae07

since the default path is useless anyway i think this is better for now, may reimplement this when #34 is done.
