### ISSUE TITLE
unnecessary dependency to fdescfs

### ISSUE THREAD

**Issue by erdgeist** [lukas2511/letsencrypt.sh#57]
The construct

<(cat "${OPENSSL_CNF}" <(printf "[SAN]\nsubjectAltName=%s" "${SAN}"))

leads to
No such file or directory:/usr/src/secure/lib/libcrypto/../../../crypto/openssl/crypto/bio/bss_file.c:126:fopen('/dev/fd/63','rb')

under FreeBSD, if fdescfs is not mounted.

A simple

  cp "${OPENSSL_CNF}" /tmp/foo.cnf
  printf "[SAN]\nsubjectAltName=%s" "${SAN}" >> /tmp/foo.cnf
  openssl req -new -sha256 -key "${BASEDIR}/certs/${domain}/${privkey}" -out "${BASEDIR}/certs/${domain}/cert-${timestamp}.csr" -subj "/CN=${domain}/" -reqexts SAN -config /tmp/foo.cnf

makes it work here.

**Comment by lukas2511** [comment]
thx
