### ISSUE TITLE
Unlisted dependency: column (from the bsdmainutils package)

### ISSUE THREAD

**Issue by olemartinorg** [lukas2511/letsencrypt.sh#66]
Hi! When i try to run the script without any parameters, it tries to use the "column" command, which may not be available on every system (but is found in the bsdmainutils package on debian/ubuntu, at least).

**Comment by lukas2511** [comment]
Interesting. I somehow assumed this to be a builtin, mh.
I'll probably just replace it with a simple printf statement in the next few days.

**Comment by lukas2511** [comment]
This should be fixed in 7727f5ea61d7993793517d4fcb72a1bde609eef2.
