### ISSUE TITLE
Default to staging to avoid rate limiting

### ISSUE THREAD

**Issue by reetp** [lukas2511/letsencrypt.sh#72]
Without realising (what you mean RTFM?!) I hit the limit quite quickly

It would help to document this fact and use the staging server by default to test.

**Comment by lukas2511** [comment]
I want this thing to kinda work out-of-the-box, and changing it to staging would probably confuse a lot of users why their new certificates are not working (anymore), so i will not do that. Sorry.

**Comment by reetp** [comment]
Can you modify the readme to make it much clearer then ?

It may save a few people a lot of problems !

**Comment by nikku** [comment]
@reetp Just provide a PR for anything that may help people circumvent this.

**Comment by aral** [comment]
Agree that default should be live but that we should warn regarding rate limit and show how to use the staging server (it’s not even mentioned at the moment and people have to hunt down the URL separately). I’ve just updated the readme with that info and added a pull request: https://github.com/lukas2511/letsencrypt.sh/pull/135 — hope it helps :)

**Comment by reetp** [comment]
Nice thanks ! 
It is easily overlooked when you are staring to play.

**Comment by theibel** [comment]
# Path to certificate authority (default: https://acme-v02.api.letsencrypt.org/directory)
#CA="https://acme-v02.api.letsencrypt.org/directory"

**Add this to the main config file:**
# Path to staging certificate authority for testing - run this first (default: none)
CA="https://acme-staging-v02.api.letsencrypt.org/directory"

When you're done testing, you can simply remove the staging files from your ${BASEDIR}, comment out the staging, and uncomment the live CA.  As it is today, each repo (live or staging) has it's own account validation. I've had success running this across several WordPress multisite setups.
