### ISSUE TITLE
Is there any installation instructions?

### ISSUE THREAD

**Issue by Amet13** [lukas2511/letsencrypt.sh#83]
Subj.

I running letsencrypt.sh first time and using this instruction: https://www.metachris.com/2015/12/comparison-of-10-acme-lets-encrypt-clients/

```
# ls
config.sh  config.sh.example  domains.txt  domains.txt.example  letsencrypt.sh  LICENSE  README.md  test.sh
# cat domains.txt
le.amet13.name
lebeta.amet13.name
# ./letsencrypt.sh
Unknown parameter detected: 
```

**Comment by mro** [comment]
yes, there are. Have a look at https://github.com/lukas2511/letsencrypt.sh#domainstxt - see the naked domain mentioned first?

**Comment by Amet13** [comment]
Not any difference.

**Comment by mro** [comment]
what did you expect to happen? Did you read https://github.com/lukas2511/letsencrypt.sh#usage ?

**Comment by Amet13** [comment]
>Did you read https://github.com/lukas2511/letsencrypt.sh#usage ?
Yes.

Can you show step by step, how can is create certificate for domain with letsencrypt.sh? I can't understand.

**Comment by mro** [comment]
I wrote down how I succeeded here: http://blog.mro.name/2015/12/lighttpd-letsencrypt-sh/

**Comment by lukas2511** [comment]
Default command has changed, you have to provide `-c` or `--cron` to actually get it to do anything.

Also the `Unknown parameter detected:` message is a bug, it should just show the help text without any errors, I'll fix that.
