### ISSUE TITLE
$WELLKNOWN / challenge-response for nginx

### ISSUE THREAD

**Issue by bobcanthelpyou** [lukas2511/letsencrypt.sh#93]
The config example for nginx in the README.md doesn't work for me
```
location /.well-known/acme-challenge {
  alias /var/www/letsencrypt;
}
```
I just get 403 forbidden errors when i try to access one of the challenge files via a browser and also letsencrypt.sh can't access the challenge files.

But the following config for nginx works for me:
```
location ^~ /.well-known/acme-challenge {
  alias /var/www/letsencrypt;
}
```

Not sure if that should be changed or if there could be an other issue preventing the example config for nginx work correctly in my setup.

**Comment by lukas2511** [comment]
I'm personally using `location /.well-known/acme-challenge { alias /var/www/letsencrypt; }`, and I don't have any problems with that. Seems to be a problem with your configuration.
