### ISSUE TITLE
Please make releases

### ISSUE THREAD

**Issue by ymc-dabe** [lukas2511/letsencrypt.sh#96]
I'm currently working on some Debian packaging for letsencrypt.sh and it would be really helpful to base this on releases (rather than some random commits in git).

Would you mind using some [version schema](https://en.wikipedia.org/wiki/Software_versioning) and do a release from time to time?

**Comment by lukas2511** [comment]
I find it really hard to decide at which point I'd want a new version release.

Things are changing all the time and it now slowly starts becoming a bit more structured and stable, but i still don't feel like marking the code as "released".

At some point I may give it a version number, but at the moment it just doesn't feel right...

**Comment by ymc-dabe** [comment]
Okay, that's alright. I [opened an ITP on bugs.debian.org](https://bugs.debian.org/812174) for a "0.0.0~2016.01.21~git23b0ef5" version. This hopefully will be a low enough version to not increase the Debian epoch, once you're doing releases of letsencrypt.sh.

For me it's okay, if you prefer to close this GitHub issue.

**Comment by lukas2511** [comment]
I've just released version 0.1.0 of this script.

**Comment by ymc-dabe** [comment]
That's just great - thanks a lot!
